### ISSUE TITLE
Warns about sourcemaps even when plugin is disabled

### ISSUE THREAD

**Issue by AndrewLeedham** [iFaxity/vite-plugin-istanbul#18]
The error message `Sourcemaps not enabled and will be automatically enabled for code coverage to be accurate.` seems to be shown regardless of whether the plugin is currently being used. Would it be feasible to check `requireEnv` etc. before trying to enable source-maps?

**Comment by iFaxity** [comment]
Hi @AndrewLeedham, _maybe_.

The message is printed when the sourcemaps config is forced.
Which is needed to be added _before_ config is resolved in accordance to other plugins.

However the requireEnv check is not made from _after_ the config is fully resolved.

This might be able to fixed in some way, this was more or less a dirty fix in order to fix a previous issue.

**Comment by iFaxity** [comment]
The "fix" to this is to just set the Vite config `build.sourcemap` to **true**.

I will be submitting a PR to allow "inline" and "hidden" aswell.

Otherwise i don't see a solution to change where the message is set without lying to the user. And probably case headaches as to why sourcemaps are being generated when the plugin is effectively disabled.

**Comment by iFaxity** [comment]
Released in v2.5.1.

**Comment by AndrewLeedham** [comment]
@iFaxity I think the confusion for me is because I am building a component library in lib mode in my `vite.config.ts`, and I don't want sourcemaps to be generated as they aren't used in the consumer and just slow things down for my use case. However, I am using the config and this plugin for Cypress, and want them enabled there.

**Comment by iFaxity** [comment]
Aha I see @AndrewLeedham. 

Personally I would recommend having different Vite configs for test and actual builds. Or conditionally applying plugins based on configuration.

An alternative is for the plugin to do the reverse, to warn the developer of there not being any sourcemaps and print a warning regarding it. This is more logical to me as setting config is a dirty fix.

**Comment by iFaxity** [comment]
I would consider the alternative solution as a breaking change and require a version bump to v3.0.0.
