### ISSUE TITLE
bug: sourcesContent isn't escaped

### ISSUE THREAD

**Issue by KaelWD** [iFaxity/vite-plugin-istanbul#8]
```js
export const IS_PROD = process.env.NODE_ENV === 'production'
```
Is transformed to
```js
sourcesContent:["export const IS_PROD = "development" === 'production'\n"]
```
Resulting in `Uncaught SyntaxError: Unexpected identifier` at runtime

**Comment by iFaxity** [comment]
Hmm, this is probably caused by an underlying API. Such as the this.getCombinedSourcemap() function returning malformed data.

This needs some investigation will make some POC project and see what causes this.

**Comment by matrunchyk** [comment]
Any updates on it? We would like to use this nice plugin for instrumentation our apps, but this issue is a real bummer for us.

**Comment by iFaxity** [comment]
Hi @matrunchyk , yes I've done some analysis on this but I cant seem to figure out in what scenario this error occurs.

The demo project used in the analysis will be uploaded soon (placeholder for link here).

Otherwise just the fact that `process.env.NODE_ENV` is replaced in @KaelWD's example it just seems that there is some other pre-processor used to replace the variable with the environment constant.

In Vite the `import.meta.env.MODE` should be used instead of the "Node" way of handling environment variables. But if it still occurs from an external package then i would think the safest way wopuld be to analyze what package it happens to and why.

To be able to debug why this happens I would need a more concrete example project where this happens. As I cannot seem to reproduce the same error.

**Comment by matrunchyk** [comment]
Oh, I didn't know about `import.meta.env.MODE`. I will try it and reply here. In all other means — I have already tried the plugin and it works as a charm! Thank you again for sharing this repo @iFaxity!

**Comment by joshwooding** [comment]
I've been investigating this recently. This is because client-inject replaces process.env.NODE_ENV https://github.com/vitejs/vite/blob/834efe94fe2c26fcdeabcc34a667dcc6a52326ee/packages/vite/src/node/plugins/clientInjections.ts#L56

I'm not sure how to work around but I'm wondering if we can just delete the sourcesContent string? As far as I can tell it's optional and istanbul-lib-instrument doesn't use it. In my local testing .tsx files don't have this field anyway.

**Comment by matrunchyk** [comment]
Wow guys you are amazing!!! 🥇 Thank you @joshwooding and @iFaxity
